######################################################################
# Automatically generated by qmake (3.0) jeu. déc. 22 12:14:15 2016
######################################################################

QT += testlib
TEMPLATE = app
TARGET = tests
INCLUDEPATH += .

# Input
SOURCES += TestTankApp.cpp \
	../tankApp/Point.cpp

# Output
DESTDIR = target/bin-tests
OBJECTS_DIR = target/bin-tests
MOC_DIR = src/tests
